#!/bin/perl

use v5.14;
use File::Basename;
use IPC::Run3 qw(run3);
use Getopt::Long qw(:config pass_through);

use lib dirname(__FILE__) . '/perl';
use Utils;

my $config = $ENV{XDG_CONFIG_HOME} . '/dwol.conf';

GetOptions ( 'config' => \$config );

my $search = @ARGV ? $ARGV[0] : '';
my $devices = Utils::parse_config $config;
my @names = keys %$devices;
my $device;

if ($search) {
     my @matches = grep /$search/i, @names;
     $device = $matches[0] if @matches == 1;
}

if (not $device) {
    my $input = join "\n", @names;
    my $lines = @names;
    my $dmenu = [
        'dmenu', '-F', '-i', '-c',
        '-l', $lines,
        '-z', '300',
        '-p', 'Server:',
        '-it', $search
    ];

    run3 $dmenu, \$input, \$device;

    chomp $device;
}

if ($device) {
    my $msg = qx(wol '$devices->{$device}');
    chomp $msg;
    system "notify-send -a dwol -i network-wireless WakeOnLan '$msg'"
}
