#!/bin/perl

use v5.14;
use File::Basename;
use IPC::Run3 qw(run3);

use lib dirname(__FILE__) . '/perl';
use Utils;

my ($options, $args) = Utils::parse_args "c:CFG:v:$ENV{XDG_CONFIG_HOME}/dwol.conf";
my $search = $args->[0] || '';

my $devices = Utils::parse_config $options->{CFG};
my @devnames = keys %$devices;
my $device;

if ($search) {
     my @matches = grep /$search/i, @devnames;
     $device = $matches[0] if @matches == 1;
}

if (not $device) {
    my $input = join "\n", @devnames;
    my $lines = @devnames;
    my $dmenu = ['dmenu', '-i', '-c', '-l', $lines, '-z', 300, '-p', 'Server:', '-it', $search];

    run3 $dmenu, \$input, \$device;

    chomp $device;
}

if ($device) {
    my $msg = qx(wol '$devices->{$device}');
    chomp $msg;
    system "notify-send -a dwol -i network-wireless WakeOnLan '$msg'"
}
