#!/bin/sh

AMOUNT=5
WHAT=paras
START=false

if ! command -v curl >/dev/null; then
    >&2 echo "curl needs to be installed"
    exit 1
fi

if ! command -v jq >/dev/null; then
    >&2 echo "jq needs to be installed"
    exit 1
fi

while getopts ":n:wpbls" opt; do
  case $opt in
    n)
      AMOUNT=$OPTARG
      ;;
    w)
      WHAT=words
      ;;
    p)
      WHAT=paras
      ;;
    b)
      WHAT=bytes
      ;;
    s)
      START=true
      ;;
    *)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

curl -s -X POST https://lipsum.com/feed/json -d "amount=$AMOUNT" -d "what=$WHAT" -d"start=$START" | jq -r '.feed.lipsum'
