#!/bin/perl

use v5.14;
use Getopt::Long;

my $length = 16;
my @setnames = qw(alnum);

GetOptions(
    'symbols' => sub { push @setnames, 'punct' },
    'digits' => sub { @setnames = qw(digit) },
    'alpha' => sub { @setnames = qw(alpha) },
    'include=s' => \@setnames,
    'number=s' => \$length,
);

my $charsets = join "", map { "[:$_:]" } @setnames;

system "LC_ALL=C tr -dc '$charsets' </dev/urandom | head -c $length && echo";
