#!/bin/sh

# USAGE: pint-stdin < MyClass.php > MyClassFormatted.php
# pint wrapper to support IO from/to stdin/stdout

if ! command -v ./vendor/bin/pint >/dev/null; then
    >&2 echo "pint not installed"
    exit 1
fi

tmpfile="$(mktemp)"
trap "rm '$tmpfile'" EXIT

cat - > "$tmpfile"
pint --quiet --no-interaction "$tmpfile"
cat "$tmpfile"
