#!/usr/bin/env python3

import socket
import sys
import os

UNKNOWN_MAC = "ff:ff:ff:ff:ff:ff"
BROADCAST_IP = "255.255.255.255"
DEFAULT_PORT = 5

def create_magic_packet(macaddress: str) -> bytes:
    """
    Create a magic packet.

    A magic packet is a packet that can be used with the for wake on lan
    protocol to wake up a computer. The packet is constructed from the
    mac address given as a parameter.

    Args:
        macaddress: the mac address that should be parsed into a magic packet.

    """
    if len(macaddress) == 17:
        sep = macaddress[2]
        macaddress = macaddress.replace(sep, "")
    elif len(macaddress) == 14:
        sep = macaddress[4]
        macaddress = macaddress.replace(sep, "")
    if len(macaddress) != 12:
        raise ValueError("Incorrect MAC address format")
    return bytes.fromhex("F" * 12 + macaddress * 16)


def send_magic_packet(
    ip_address: str = BROADCAST_IP,
    port: int = DEFAULT_PORT,
    *macs: str,
) -> None:
    """
    Wake up computers having any of the given mac addresses.

    Wake on lan must be enabled on the host device.

    Args:
        macs: One or more macaddresses of machines to wake.

    Keyword Args:
        ip_address: the ip address of the host to send the magic packet
            to.
        port: the port of the host to send the magic packet to.
        interface: the ip address of the network adapter to route the
            magic packet through.
    """
    packets = [create_magic_packet(mac) for mac in macs]

    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        sock.connect((ip_address, port))
        for packet in packets:
            sock.send(packet)


def main():
    args = sys.argv[1:]
    macs = []
    ip = BROADCAST_IP
    port = DEFAULT_PORT
    i = 0

    while i < len(args):
        arg = args[i]

        if arg == "-i" or arg == "--ip":
            ip = args[i+1]
            i += 1
        elif arg == "-p" or arg == "--port":
            port = int(args[i+1])
            i += 1
        elif arg == "-h" or arg == "--help":
            print("USAGE: wol [-h|--help] [-i|--ip BROADCAST_IP] [-p|--port PORT] [MAC...]")
            return
        else:
            home_dir = os.environ.get("HOME", "")
            config_dir = os.environ.get("XDG_CONFIG_HOME", os.path.join(home_dir, ".config"))
            path = os.path.join(config_dir, "wol", arg)

            with open(path) as f:
                mac = f.readline().strip()
                macs.append(mac)

        i += 1

    send_magic_packet(ip, port, *macs)

if __name__ == "__main__":
    main()
